<template>
  <app-layout>
    <div class="page-header">
      <div>
        <h1 class="page-title">Daily Summary Email</h1>
        <p class="page-sub">Preview & send the operations snapshot</p>
      </div>
      <div class="page-header-actions">
        <button class="btn btn--ghost btn--sm">
          <svg-icon name="download" :size="15" /> Export PDF
        </button>
        <button class="btn btn--primary btn--sm" :disabled="!recipients.length || sending" @click="send">
          <svg-icon name="send" :size="15" /> {{ sending ? 'Sending…' : `Send to ${recipients.length} recipients` }}
        </button>
      </div>
    </div>

    <div v-if="sent" class="sent-banner">
      Email sent successfully to {{ recipients.length }} recipients.
    </div>

    <!-- Email preview -->
    <div class="email-preview">
      <div class="email-meta">
        <div class="email-meta-row"><span class="meta-label">From:</span> <span>NAQLA LMS &lt;lms@naqla.org&gt;</span></div>
        <div class="email-meta-row"><span class="meta-label">To:</span> <span>{{ recipientSummary }}</span></div>
        <div class="email-meta-row"><span class="meta-label">Subject:</span> <span>Logistics Snapshot · {{ eventName }} · {{ prettyDate }}</span></div>
      </div>

      <div class="email-body">
        <div class="email-header-block">
          <div class="email-logo-row">
            <span class="email-logo-mark">LMS</span>
            <span class="email-logo-name">{{ eventName }} · Logistics</span>
          </div>
          <div class="email-title-row">
            <span class="email-title">Daily Operations Snapshot</span>
            <span class="email-date">{{ prettyDate }}</span>
          </div>
        </div>

        <!-- KPI summary -->
        <div class="email-section">
          <div class="email-section-title">Key Performance Indicators</div>
          <div class="email-kpi-grid">
            <div v-for="kpi in kpis.slice(0, 6)" :key="kpi.id" class="email-kpi">
              <div class="email-kpi-label">{{ kpi.label }}</div>
              <div class="email-kpi-value">{{ kpi.value }}</div>
              <div :class="['email-kpi-delta', `email-kpi-delta--${kpi.tone}`]">{{ kpi.delta }}</div>
            </div>
          </div>
        </div>

        <!-- Today's movements -->
        <div class="email-section">
          <div class="email-section-title">Today's Movements</div>
          <table class="email-table">
            <thead><tr>
              <th>Job</th><th>Team</th><th>Route</th><th>Window</th><th>Status</th>
            </tr></thead>
            <tbody>
              <tr v-for="mv in schedule" :key="mv.id">
                <td class="mono">{{ mv.id }}</td>
                <td>{{ mv.team }}</td>
                <td>{{ mv.from }} → {{ mv.to }}</td>
                <td class="mono">{{ mv.dep }}–{{ mv.arr }}</td>
                <td :class="`status-${mv.status}`">{{ mv.status }}</td>
              </tr>
              <tr v-if="!schedule.length">
                <td colspan="5">No movements scheduled for this day.</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="email-footer">
          Generated by NAQLA LMS · {{ prettyDate }} · Confidential
        </div>
      </div>
    </div>
  </app-layout>
</template>

<script setup>
import { computed, ref } from 'vue';
import { router } from '@inertiajs/vue3';
import AppLayout from '../Components/AppLayout.vue';
import SvgIcon from '../Components/SvgIcon.vue';
import { useToast } from '../Composables/useToast';

const props = defineProps({
  schedule:   { type: Array, default: () => [] },
  kpis:       { type: Array, default: () => [] },
  recipients: { type: Array, default: () => [] },
  event:      { type: Object, default: null },
  date:       { type: String, default: '' },
});

const { success: showSuccessToast, error: showErrorToast } = useToast();

const sending = ref(false);
const sent = ref(false);

function send() {
  router.post('/email/send', { date: props.date }, {
    preserveScroll: true,
    onStart: () => { sending.value = true; },
    onFinish: () => { sending.value = false; },
    onSuccess: (page) => {
      const flash = page.props.flash || {};
      if (flash.error) {
        showErrorToast(flash.error);
        return;
      }
      sent.value = true;
      showSuccessToast(flash.success || 'Daily summary sent.');
    },
    onError: () => showErrorToast('Could not send the daily summary.'),
  });
}

const eventName = computed(() => props.event?.short_name || props.event?.name || 'NAQLA LMS');

const prettyDate = computed(() => (props.date
  ? new Date(`${props.date}T00:00:00`).toLocaleDateString(undefined, {
      weekday: 'short', day: '2-digit', month: 'short', year: 'numeric',
    })
  : ''));

const recipientSummary = computed(() => {
  if (!props.recipients.length) return 'No recipients assigned to this event';
  const names = props.recipients.slice(0, 3).map((r) => r.name).join(' · ');
  const rest = props.recipients.length - 3;
  return rest > 0 ? `${names} +${rest} more (${props.recipients.length})` : `${names} (${props.recipients.length})`;
});
</script>

<style scoped>
.page-header {
  display: flex; align-items: flex-start; justify-content: space-between;
  gap: 12px; margin-bottom: 16px; flex-wrap: wrap;
}
.page-title { font-size: 20px; font-weight: 700; color: var(--ink); margin: 0 0 2px; }
.page-sub { font-size: 13px; color: var(--ink3); margin: 0; }
.page-header-actions { display: flex; gap: 8px; }
.btn {
  display: inline-flex; align-items: center; gap: 5px;
  border-radius: 7px; font-size: 13px; font-weight: 500; cursor: pointer;
  border: 1px solid transparent;
}
.btn--sm { padding: 6px 12px; }
.btn--ghost { background: none; border-color: var(--border); color: var(--ink3); }
.btn--ghost:hover { background: var(--panel); color: var(--ink); }
.btn--primary { background: var(--accent); color: #fff; }
.btn--primary:hover { opacity: 0.9; }
.btn:disabled { opacity: 0.5; cursor: not-allowed; }

.sent-banner {
  background: var(--ok-soft); color: var(--ok); border: 1px solid var(--ok);
  border-radius: 8px; padding: 10px 16px; margin-bottom: 14px; font-size: 13.5px; font-weight: 600;
}

.email-preview {
  background: var(--surface); border: 1px solid var(--border);
  border-radius: 10px; overflow: hidden; max-width: 720px;
}
.email-meta {
  padding: 14px 20px; border-bottom: 1px solid var(--border);
  display: flex; flex-direction: column; gap: 4px; background: var(--panel);
}
.email-meta-row { font-size: 13px; color: var(--ink2); }
.meta-label { font-weight: 600; color: var(--ink3); margin-right: 6px; width: 60px; display: inline-block; }
.email-body { padding: 24px; }

.email-header-block { margin-bottom: 24px; }
.email-logo-row { display: flex; align-items: center; gap: 8px; margin-bottom: 12px; }
.email-logo-mark {
  background: var(--accent); color: #fff;
  font-size: 11px; font-weight: 700; padding: 3px 8px; border-radius: 5px;
}
.email-logo-name { font-size: 13px; color: var(--ink3); }
.email-title-row { display: flex; align-items: baseline; justify-content: space-between; }
.email-title { font-size: 22px; font-weight: 800; color: var(--ink); }
.email-date { font-size: 13px; color: var(--ink3); }

.email-section { margin-bottom: 24px; }
.email-section-title {
  font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em;
  color: var(--ink3); margin-bottom: 12px; padding-bottom: 6px;
  border-bottom: 1px solid var(--border);
}

.email-kpi-grid {
  display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr)); gap: 12px;
}
.email-kpi {
  background: var(--panel); border: 1px solid var(--border);
  border-radius: 8px; padding: 12px;
}
.email-kpi-label { font-size: 11px; color: var(--ink3); margin-bottom: 4px; }
.email-kpi-value { font-size: 18px; font-weight: 700; color: var(--ink); }
.email-kpi-delta { font-size: 12px; font-weight: 600; margin-top: 2px; }
.email-kpi-delta--ok      { color: var(--ok); }
.email-kpi-delta--warn    { color: var(--warn); }
.email-kpi-delta--danger  { color: var(--danger); }
.email-kpi-delta--primary { color: var(--accent-fg); }
.email-kpi-delta--neutral { color: var(--ink3); }

.email-table { width: 100%; border-collapse: collapse; font-size: 13px; }
.email-table th {
  text-align: left; padding: 7px 10px;
  font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;
  color: var(--ink3); border-bottom: 1px solid var(--border); background: var(--panel);
}
.email-table td { padding: 9px 10px; border-bottom: 1px solid var(--border); }
.email-table tr:last-child td { border-bottom: none; }
.mono { font-family: var(--font-mono, monospace); font-size: 12px; }
.status-in-progress { color: var(--live); font-weight: 600; }
.status-delayed     { color: var(--warn); font-weight: 600; }
.status-done        { color: var(--ok); font-weight: 600; }
.status-scheduled   { color: var(--ink3); }

.email-footer {
  margin-top: 24px; padding-top: 16px;
  border-top: 1px solid var(--border);
  font-size: 11.5px; color: var(--ink4); text-align: center;
}
</style>
