<template>
  <app-layout>
    <div class="page-header">
      <div>
        <h1 class="page-title">Daily Summary Email</h1>
        <p class="page-sub">Preview & send the operations snapshot</p>
      </div>
      <div class="page-header-actions">
        <button class="btn btn--ghost btn--sm">
          <svg-icon name="download" :size="15" /> Export PDF
        </button>
        <button class="btn btn--primary btn--sm" @click="sent = true">
          <svg-icon name="send" :size="15" /> Send to 23 recipients
        </button>
      </div>
    </div>

    <div v-if="sent" class="sent-banner">
      Email sent successfully to 23 recipients.
    </div>

    <!-- Email preview -->
    <div class="email-preview">
      <div class="email-meta">
        <div class="email-meta-row"><span class="meta-label">From:</span> <span>Atlas Cup LMS &lt;lms@atlascup2026.org&gt;</span></div>
        <div class="email-meta-row"><span class="meta-label">To:</span> <span>Exec Team · Partner Groups (23)</span></div>
        <div class="email-meta-row"><span class="meta-label">Subject:</span> <span>Logistics Snapshot · Match Day 4 · {{ $page.props.today }}</span></div>
      </div>

      <div class="email-body">
        <div class="email-header-block">
          <div class="email-logo-row">
            <span class="email-logo-mark">LMS</span>
            <span class="email-logo-name">Atlas Cup 2026 · Logistics</span>
          </div>
          <div class="email-title-row">
            <span class="email-title">Daily Operations Snapshot</span>
            <span class="email-date">{{ $page.props.today }}</span>
          </div>
        </div>

        <!-- KPI summary -->
        <div class="email-section">
          <div class="email-section-title">Key Performance Indicators</div>
          <div class="email-kpi-grid">
            <div v-for="kpi in kpis.slice(0, 6)" :key="kpi.id" class="email-kpi">
              <div class="email-kpi-label">{{ kpi.label }}</div>
              <div class="email-kpi-value">{{ kpi.value }}</div>
              <div :class="['email-kpi-delta', `email-kpi-delta--${kpi.tone}`]">{{ kpi.delta }}</div>
            </div>
          </div>
        </div>

        <!-- Today's movements -->
        <div class="email-section">
          <div class="email-section-title">Today's Movements</div>
          <table class="email-table">
            <thead><tr>
              <th>Job</th><th>Team</th><th>Route</th><th>Window</th><th>Status</th>
            </tr></thead>
            <tbody>
              <tr v-for="mv in schedule" :key="mv.id">
                <td class="mono">{{ mv.id }}</td>
                <td>{{ mv.team }}</td>
                <td>{{ mv.from }} → {{ mv.to }}</td>
                <td class="mono">{{ mv.dep }}–{{ mv.arr }}</td>
                <td :class="`status-${mv.status}`">{{ mv.status }}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="email-footer">
          Generated by Atlas Cup LMS · {{ $page.props.today }} · Confidential
        </div>
      </div>
    </div>
  </app-layout>
</template>

<script setup>
import { ref } from 'vue';
import AppLayout from '../Components/AppLayout.vue';
import SvgIcon from '../Components/SvgIcon.vue';

defineProps({
  schedule: { type: Array, default: () => [] },
  kpis:     { type: Array, default: () => [] },
});

const sent = ref(false);
</script>

<style scoped>
.page-header {
  display: flex; align-items: flex-start; justify-content: space-between;
  gap: 12px; margin-bottom: 16px; flex-wrap: wrap;
}
.page-title { font-size: 20px; font-weight: 700; color: var(--ink); margin: 0 0 2px; }
.page-sub { font-size: 13px; color: var(--ink3); margin: 0; }
.page-header-actions { display: flex; gap: 8px; }
.btn {
  display: inline-flex; align-items: center; gap: 5px;
  border-radius: 7px; font-size: 13px; font-weight: 500; cursor: pointer;
  border: 1px solid transparent;
}
.btn--sm { padding: 6px 12px; }
.btn--ghost { background: none; border-color: var(--border); color: var(--ink3); }
.btn--ghost:hover { background: var(--panel); color: var(--ink); }
.btn--primary { background: var(--accent); color: #fff; }
.btn--primary:hover { opacity: 0.9; }

.sent-banner {
  background: var(--ok-soft); color: var(--ok); border: 1px solid var(--ok);
  border-radius: 8px; padding: 10px 16px; margin-bottom: 14px; font-size: 13.5px; font-weight: 600;
}

.email-preview {
  background: var(--surface); border: 1px solid var(--border);
  border-radius: 10px; overflow: hidden; max-width: 720px;
}
.email-meta {
  padding: 14px 20px; border-bottom: 1px solid var(--border);
  display: flex; flex-direction: column; gap: 4px; background: var(--panel);
}
.email-meta-row { font-size: 13px; color: var(--ink2); }
.meta-label { font-weight: 600; color: var(--ink3); margin-right: 6px; width: 60px; display: inline-block; }
.email-body { padding: 24px; }

.email-header-block { margin-bottom: 24px; }
.email-logo-row { display: flex; align-items: center; gap: 8px; margin-bottom: 12px; }
.email-logo-mark {
  background: var(--accent); color: #fff;
  font-size: 11px; font-weight: 700; padding: 3px 8px; border-radius: 5px;
}
.email-logo-name { font-size: 13px; color: var(--ink3); }
.email-title-row { display: flex; align-items: baseline; justify-content: space-between; }
.email-title { font-size: 22px; font-weight: 800; color: var(--ink); }
.email-date { font-size: 13px; color: var(--ink3); }

.email-section { margin-bottom: 24px; }
.email-section-title {
  font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em;
  color: var(--ink3); margin-bottom: 12px; padding-bottom: 6px;
  border-bottom: 1px solid var(--border);
}

.email-kpi-grid {
  display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr)); gap: 12px;
}
.email-kpi {
  background: var(--panel); border: 1px solid var(--border);
  border-radius: 8px; padding: 12px;
}
.email-kpi-label { font-size: 11px; color: var(--ink3); margin-bottom: 4px; }
.email-kpi-value { font-size: 18px; font-weight: 700; color: var(--ink); }
.email-kpi-delta { font-size: 12px; font-weight: 600; margin-top: 2px; }
.email-kpi-delta--ok      { color: var(--ok); }
.email-kpi-delta--warn    { color: var(--warn); }
.email-kpi-delta--danger  { color: var(--danger); }
.email-kpi-delta--primary { color: var(--accent-fg); }
.email-kpi-delta--neutral { color: var(--ink3); }

.email-table { width: 100%; border-collapse: collapse; font-size: 13px; }
.email-table th {
  text-align: left; padding: 7px 10px;
  font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;
  color: var(--ink3); border-bottom: 1px solid var(--border); background: var(--panel);
}
.email-table td { padding: 9px 10px; border-bottom: 1px solid var(--border); }
.email-table tr:last-child td { border-bottom: none; }
.mono { font-family: var(--font-mono, monospace); font-size: 12px; }
.status-in-progress { color: var(--live); font-weight: 600; }
.status-delayed     { color: var(--warn); font-weight: 600; }
.status-done        { color: var(--ok); font-weight: 600; }
.status-scheduled   { color: var(--ink3); }

.email-footer {
  margin-top: 24px; padding-top: 16px;
  border-top: 1px solid var(--border);
  font-size: 11.5px; color: var(--ink4); text-align: center;
}
</style>
