@php
    $event = $summary['event']['short_name'] ?? $summary['event']['name'] ?? 'NAQLA LMS';
    $date = \Carbon\Carbon::parse($summary['date'])->format('D, d M Y');
@endphp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Daily Operations Snapshot</title>
</head>
<body style="margin:0;padding:24px;background:#f4f5f7;font-family:Arial,Helvetica,sans-serif;color:#1f2430;">
<div style="max-width:720px;margin:0 auto;background:#ffffff;border:1px solid #e3e6ea;border-radius:10px;padding:24px;">
    <div style="margin-bottom:24px;">
        <span style="background:#2563eb;color:#fff;font-size:11px;font-weight:700;padding:3px 8px;border-radius:5px;">LMS</span>
        <span style="font-size:13px;color:#5b6472;margin-left:8px;">{{ $event }} · Logistics</span>
    </div>

    <h1 style="font-size:22px;margin:0 0 4px;">Daily Operations Snapshot</h1>
    <p style="font-size:13px;color:#5b6472;margin:0 0 24px;">{{ $date }}</p>

    <h2 style="font-size:12px;text-transform:uppercase;letter-spacing:0.08em;color:#5b6472;border-bottom:1px solid #e3e6ea;padding-bottom:6px;">
        Key Performance Indicators
    </h2>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;">
        <tr>
            @foreach ($summary['kpis'] as $kpi)
                <td style="padding:8px 8px 8px 0;vertical-align:top;width:20%;">
                    <div style="background:#f8f9fb;border:1px solid #e3e6ea;border-radius:8px;padding:12px;">
                        <div style="font-size:11px;color:#5b6472;">{{ $kpi['label'] }}</div>
                        <div style="font-size:18px;font-weight:700;">{{ $kpi['value'] }}</div>
                        <div style="font-size:11px;color:#5b6472;">{{ $kpi['delta'] }}</div>
                    </div>
                </td>
            @endforeach
        </tr>
    </table>

    <h2 style="font-size:12px;text-transform:uppercase;letter-spacing:0.08em;color:#5b6472;border-bottom:1px solid #e3e6ea;padding-bottom:6px;">
        Today's Movements
    </h2>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;font-size:13px;">
        <thead>
        <tr style="background:#f8f9fb;">
            <th align="left" style="padding:7px 10px;font-size:11px;color:#5b6472;">Job</th>
            <th align="left" style="padding:7px 10px;font-size:11px;color:#5b6472;">Team</th>
            <th align="left" style="padding:7px 10px;font-size:11px;color:#5b6472;">Route</th>
            <th align="left" style="padding:7px 10px;font-size:11px;color:#5b6472;">Window</th>
            <th align="left" style="padding:7px 10px;font-size:11px;color:#5b6472;">Status</th>
        </tr>
        </thead>
        <tbody>
        @forelse ($summary['schedule'] as $mv)
            <tr>
                <td style="padding:9px 10px;border-bottom:1px solid #e3e6ea;">{{ $mv['id'] }}</td>
                <td style="padding:9px 10px;border-bottom:1px solid #e3e6ea;">{{ $mv['team'] }}</td>
                <td style="padding:9px 10px;border-bottom:1px solid #e3e6ea;">{{ $mv['from'] }} &rarr; {{ $mv['to'] }}</td>
                <td style="padding:9px 10px;border-bottom:1px solid #e3e6ea;">{{ $mv['dep'] }}&ndash;{{ $mv['arr'] }}</td>
                <td style="padding:9px 10px;border-bottom:1px solid #e3e6ea;">{{ $mv['status'] }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="5" style="padding:9px 10px;color:#5b6472;">No movements scheduled for this day.</td>
            </tr>
        @endforelse
        </tbody>
    </table>

    <p style="margin-top:24px;padding-top:16px;border-top:1px solid #e3e6ea;font-size:11px;color:#8b93a1;text-align:center;">
        Generated by NAQLA LMS · {{ $date }} · Confidential
    </p>
</div>
</body>
</html>
